query GetDefaultFilters {
  getDefaultFilters {
    categories {
      id
      name
      count
    }
    priceRange {
      min
      max
    }
    formats {
      format
      count
    }
    tags
    sortOptions {
      value
      label
    }
    assetName
    totalCount
  }
}
